version: "3.9"

services:
  middle:
    build: .  
    image: annotator-middle:1.1.1
    command: >
      sh -c "flask db upgrade && flask run --host=0.0.0.0"
    ports:
      - "5000"
    environment:
      SECRECT_KEY: "topSecret"
      DATABASE_URI: postgresql://user:theBigSecret@db/annotations
      APP_SETTINGS: config.DevelopmentConfig
    depends_on: 
      db:
        condition: service_healthy

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: annotations
      POSTGRES_USER: user
      POSTGRES_PASSWORD: theBigSecret
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "annotations"]
      interval: 5s
      retries: 5
    volumes:
      - annotator_db:/var/lib/postgresql/data

  ui:
    build: 
      context: ./annotation-ui/
      dockerfile: Dockerfile.dev
    image: annotator-ui-dev:0.0.1
    user: $UID:$GID
    command: ng serve --host 0.0.0.0
    ports:
      - "4200"
    volumes: 
      - ./annotation-ui/:/app/

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - middle
      - ui
    
volumes:
  annotator_db:

