version: "3.9"

services:
  middle:
    build: .  
    image: annotator-middle:1.0.0
    command: >
      sh -c "flask db upgrade && pytest"
    environment:
      SECRECT_KEY: "topSecret"
      DATABASE_URI: postgresql://user:theBigSecret@db/tests
      APP_SETTINGS: config.TestingConfig
    depends_on: 
      db:
        condition: service_healthy

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: tests
      POSTGRES_USER: user
      POSTGRES_PASSWORD: theBigSecret
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "tests"]
      interval: 5s
      retries: 5
     
