"""empty message

Revision ID: ddf5fcf26890
Revises: e6070646e059
Create Date: 2021-09-20 07:37:15.637145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf5fcf26890'
down_revision = 'e6070646e059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'annotations', ['domain', 'url'])
    op.create_unique_constraint(None, 'domains', ['name', 'index_page'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'domains', type_='unique')
    op.drop_constraint(None, 'annotations', type_='unique')
    # ### end Alembic commands ###
